### ISSUE TITLE
Example code isn't working

### ISSUE THREAD

**Issue by jengeb** [justforuse/vue-mathjax#1]
I've tried to include the vue-mathjax npm package to my project, but the math formula is just dublicated without being rendered as expected – and as seen in the animation.

I added the code of the usage part of your README to the following sandbox: 
https://codesandbox.io/s/ll919qy8mq

Do I miss something to get the code running properly?

**Comment by ericbae** [comment]
Getting the same error here.

**Comment by jengeb** [comment]
Thanks for your help and for updating the README file. I wasn't aware of the need to add MathJax separately. Have you thought about adding this dependency to your package in order to save the extra inclusion of MathJax?

**Comment by justforuse** [comment]
@jengeb  yeah, I have thought about this, but it not work if you `import 'mathjax'`, and I found there are a lot of questions about how to use mathjax with npm not use cdn.. and I didn't find a proper way to use mathjax as a npm package, if you find a solution, I'd be glad to know😊.

**Comment by havvtom** [comment]
@justforuse I am trying to use vue-mathjax in my nuxt project. I have tried evrything and copied and pasted the code from the codesandbox but I am still getting plain text. May you help?
