### ISSUE TITLE
How do I prevent MathJax from showing raw TeX while waiting for rendering to complete?

### ISSUE THREAD

**Issue by Mohitpokra** [justforuse/vue-mathjax#10]
#Stackoverflow: Question https://stackoverflow.com/questions/29722813/how-do-i-prevent-mathjax-from-showing-raw-tex-while-waiting-for-rendering-to-com

Not clear about What can we pass in options prop?

**Comment by justforuse** [comment]
I think you mean the `options` prop, check the code: https://github.com/justforuse/vue-mathjax/blob/65bc0a05b7240044a05c12d1e16578c8a4f9d9ad/src/components/vue-mathjax.vue#L56

**Comment by justforuse** [comment]
Let me know if it help you😀

**Comment by Mohitpokra** [comment]
Thanks for your reply @justforuse but when I am giving " Preview : none" to option prop still it is showing raw latex.

I would like nothing to appear until the MathJax has finished processing my equations: no raw LaTeX.

Is there a way to accomplish this with any config settings?

**Comment by justforuse** [comment]
@Mohitpokra I see.. maybe you should write like this:
```
const params = {
	tex2jax: {
        inlineMath: [['$', '$'], ['(', ')']],
        displayMath: [['$$', '$$'], ['[', ']']],
        processEscapes: true,
        processEnvironments: true,
+		preview: "none"
    }
}

// component.vue

:options="params"
```

**Comment by Mohitpokra** [comment]
Thanks to @justforuse. It is working perfectly 👍
