### ISSUE TITLE
HTML5 | MathML <mrow> Tag 

### ISSUE THREAD

**Issue by MohamedAhmed12** [justforuse/vue-mathjax#12]
Can I use HTML5 | MathML <mrow> Tag with  vue-mathjax package ?

**as in this example:**
data () {
    return {
      formula: `<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
                           <mrow mathsize="18px">
                                <mi>f</mi><mfenced><mi>x</mi></mfenced>
                                 <mo>=</mo><msup><mi>x</mi><mn>2</mn></msup>
                          </mrow>
                       </math>`,
      msg: 'Welcome to Your Vue.js App'
    }
  }      

I have tired it but it only display it as string

**Comment by justforuse** [comment]
Maybe not, In my opinion, MathML is HTML5 element, it is supported by browser, wheile Mathjax is a library, it is supported by JavaScript.

And MathML is not supported by main browser: Reference:

![image](https://user-images.githubusercontent.com/11868477/80678150-f248e580-8aec-11ea-8409-732041d365f2.png)
