### ISSUE TITLE
@justforuse I am trying to use vue-mathjax in my nuxt project. I have tried evrything and copied and pasted the code from the codesandbox but I am still getting plain text. May you help?

### ISSUE THREAD

**Issue by havvtom** [justforuse/vue-mathjax#14]

**Comment by justforuse** [comment]
I'm not familiar with nuxt.js maybe you can check #18 , and look for some help😁

**Comment by MohammadKhalaji** [comment]
Hey, 

First, install `vue-mathjax` and include the javascript, as mentioned in the docs. 

Create `mjx.js` in your `plugins` folder, and write this: 

`
import Vue from 'vue'
import VueMathjax from 'vue-mathjax'
Vue.use(VueMathjax)

`

Then, add this objects to your `plugins` in `nuxt.config.js` :
`
{
		    src: '~/plugins/mjx.js',
		    mode: 'client'
		}
`

**Comment by moh1434** [comment]
You need to import the original [mathJax library](https://docs.mathjax.org/en/v2.7-latest/start.html) also.
Something like:
```
<Script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_HTML">
```

**Comment by justforuse** [comment]
Remember to add Mathjax js file, `nuxt.config.js`:

```js
export default {
	head: {
		// ...
		script: [
	      {
	        src: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_HTML'
	      }
	    ]
	}
}
```

and use in page:

```
<template>
	<vue-mathjax :formula="formula"></vue-mathjax>
</template>
import { VueMathjax } from 'vue-mathjax'

export default {
  name: 'NuxtTutorial',
  components: {
    VueMathjax,
  },
  data() {
    return {
      formula: '$$x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a}.$$',
    }
  },
}

```

Works well:
![image](https://user-images.githubusercontent.com/11868477/194845397-bf90f518-fe35-4316-b2dc-19bb9eee000b.png)
