### ISSUE TITLE
Rendering string inside ()

### ISSUE THREAD

**Issue by yahrdy** [justforuse/vue-mathjax#19]
When I write something inside (), it is considered as math equation. I want to skip rendering something that is inside (). Any way to do so?

**Comment by hjy1210** [comment]
try 
`<span>(</span>x^2)`
instead of 
`(x^2)`

**Comment by yahrdy** [comment]
It solves the problem, but not efficient. I think, the rules should be changed. 
To solve the problem, I compiled my code for production and then changed the rules in the rendered javascript file.
