### ISSUE TITLE
Use single $ will not be format?

### ISSUE THREAD

**Issue by kuroikenshi** [justforuse/vue-mathjax#2]
As the title. Formula use $$ can be format as math style. But use $ can not be format. $ is formatted inline as some doc say, but official demo use $$ only. Is $ not support ?

Sorry, I‘m confused. I think vue-mathjax was same as mathjax and I missed 
```
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
</script>
```
in document of mathJax. 
Maybe vue-mathjax support tex2jax or inlineMath settings?

**Comment by justforuse** [comment]
I tried.https://codesandbox.io/s/l44n3lj487
 I found if you change the formula to trigger rerender, it performs well, I think at first time the Mathjax just not ready. it's a problem😥

**Comment by justforuse** [comment]
upgrade to latest
