### ISSUE TITLE
AsciiMath

### ISSUE THREAD

**Issue by ChristianVaughn** [justforuse/vue-mathjax#20]
Does this support AsciiMath Rendering? I am importing a version of MathJax that supports Ascii Math, but it will not display when I use backticks surrounding my ascii math equations. Also if I try just a Latex equation and right click for the context menu then I only see MathML and Laxtex/Tex and no ascii math option

**Comment by hjy1210** [comment]
If use only AsciiMath, we can put
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=AM_CHTML"></script>
```
in head part of index.html.

See: [MathJax 2.7 Docs](http://docs.mathjax.org/en/v2.7-latest/config-files.html#the-am-chtml-configuration-file)
