### ISSUE TITLE
how to import mathjax@2.7.2 in vue as local dependency?

### ISSUE THREAD

**Issue by qwtfy** [justforuse/vue-mathjax#27]
im using vue-mathJax in my project and in the readme it says to use cdn of mathJax
works fine with the CDN version

im need to use mathJax(v. 2.7.2) as local as dependency for my project but dont know how to import it with the correct configurations

how do yout set the configuration same as with the cdn version?

**CDN**

    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_HTML"></script>

**Local import after installing with npm**

    //main.js
    import '../node_modules/mathjax/MathJax?config=TeX-AMS_HTML'

**error**

    Uncaught SyntaxError: Unexpected token '<'

**Comment by justforuse** [comment]
Sorry, I am not good at this, if you have known how to do it, please add a comment under this issue😊
