### ISSUE TITLE
v-html issues

### ISSUE THREAD

**Issue by agmt5989** [justforuse/vue-mathjax#6]
So I have questions that could potentially contain tex-formatted formulae _and_ html. using the `<vue-mathjax :formula="currentQuestion.q"></vue-mathjax>` syntax, I can only get one benefit at a time - HTML rendering or mathjax rendering. How do I get both?

**Comment by justforuse** [comment]
You means when you write html code in your formula, the html text should be rendered as html, and mathjax text should be rendered as mathjax formula? 

like this ?
```
<vue-mathjax :formula="formula"></vue-mathjax>
<div v-html="formula"></div>
```
![image](https://user-images.githubusercontent.com/11868477/59050936-3ec87880-88be-11e9-8576-6b985415c886.png)


it may be a good idea, but in general, **we should not always trust user's input**, it maybe harmful.

anyways, I will try to make it.

**Comment by agmt5989** [comment]
Well, thanks. The content of that payload is not coming from user-supplied input. These are questions that we have made ourselves. Sometimes we have `<br>` tags in the question, or others like `<i>`, `<u>` or `<b>` elements to make the questions make semantic sense. 

> Find the nearest in meaning to the words underlined.
So, in a case where this happens, so far, I have been forced to use the regular `<p>` element with `v-html` attributes while using `vue`'s `this.$nextTick` to rerender on change. Surely this is not the best.

I shall await your update :100:

**Comment by agmt5989** [comment]
Still waiting for this feature.

**Comment by justforuse** [comment]
@agmt5989 sorry, these days is busy...

I update this to `0.0.9`, and it has a new prop named `safe`, if you set it false, it will render your html code

here is a demo: https://codesandbox.io/s/vue-template-ftd5s

**Comment by agmt5989** [comment]
Thank you so much. You're a life saver.

iMyke Smartphone
